#!/usr/bin/env python3
"""repo_sync.py — repo-template-sync 机械化执行器。

把 repo-template-sync skill 中可机械化对齐的部分下沉到脚本执行：硬同步清单
树对树覆盖、skill 整目录覆盖、软链建修、.gitignore / .prettierignore / MCP 机械合并、
sync_state.json 字段级原子更新、差异评估与修改路径清单输出。

非机械化裁定（AGENTS.md 等共享文稿的语义合并）由脚本给出
分类与差异摘要，agent 审查后通过 `--decision UNIT:DISPOSITION` 决策，apply
按决策写盘；未提供决策的裁定单元跳过并报告（ask_user 语义）。

用法：
  python3 .repo_template/scripts/repo_sync.py init --source <path|url>
  python3 .repo_template/scripts/repo_sync.py status
  python3 .repo_template/scripts/repo_sync.py plan
  python3 .repo_template/scripts/repo_sync.py prep
  python3 .repo_template/scripts/repo_sync.py apply [--decision AGENTS.md:update]... [--skip-tests]
  python3 .repo_template/scripts/repo_sync.py prompt list
  python3 .repo_template/scripts/repo_sync.py prompt add --text "..." [--tags a,b]
  python3 .repo_template/scripts/repo_sync.py prompt revoke --id N
  python3 .repo_template/scripts/repo_sync.py link-skills
  python3 .repo_template/scripts/repo_sync.py install-hooks [--force]

本脚本处理模板工具链与模板侧资产，并在 apply 时强制迁移 active/backlog task 的 workflow schema；不碰业务代码。禁止自动 commit——写盘与 state 更新完成后由 agent 走审批门禁。
"""

import argparse
import json
import os
import re
import shutil
import subprocess
import sys
from pathlib import Path

TOOLKIT_ROOT = Path(__file__).resolve().parent.parent
CONSUMER = TOOLKIT_ROOT.parent
STATE_PATH = CONSUMER / ".repo_template/sync_state.json"
# 旧布局 state（2026-08-15 a9453b1 前）：宿主 skill 目录下的真实目录。
# 首次在新路径 init 时读一次并迁移，避免 user_prompts / last_synced_* 丢失。
LEGACY_STATE_PATH = CONSUMER / ".agents/skills/repo-template-sync/sync_state.json"
SKILLS_SRC = CONSUMER / ".repo_template/skills"
SKILLS_AGENTS = CONSUMER / ".agents/skills"
SKILLS_CLAUDE = CONSUMER / ".claude/skills"
COMMANDS_OPENCODE = CONSUMER / ".opencode/commands"
COMMAND_MARKER = "Auto-generated by repo_sync.py from skill"
PRODUCT_MARKER = ".repo_template/scripts/task.py"

# 硬同步：整包工具链 + 宿主必须落在仓根的文件。
HARD_SYNC_DIRS = (".repo_template",)
HARD_SYNC_FILES = (
    ".md_kx.toml",
)
NOISE_NAMES = {"__pycache__", ".pytest_cache", ".DS_Store"}
PROTECT_NAMES = {"sync_state.json"}

# 裁定范围：可定制共享资产。.gitignore / .prettierignore / MCP 机械合并；AGENTS.md 语义合并。
SHARED_FILES = ("AGENTS.md", ".gitignore")

# 消费仓 apply / 默认门禁只跑模板契约，不含工厂全量集成测试。
CONSUMER_TEST_COMMAND = ("pytest", ".repo_template/tests/", "-q", "-m", "contract")
CONSUMER_TEST_TIMEOUT = 60

# AGENTS.md 同步协议：按固定标题识别三类内容。
# 项目介绍永不更新；目录与读写规则只报告差异，由 agent 语义合并；开发原则每轮强制更新。
AGENTS_INTRO_HEADING = "## 目录与读写规则"
AGENTS_MERGE_HEADING = "## 目录与读写规则"
AGENTS_FORCE_HEADING = "## 开发原则"
MCP_CANDIDATES = (".mcp.json", ".cursor/mcp.json", ".vscode/mcp.json")

# 模板自有路径：不受消费仓 prettier 门禁约束（Issue #3）。
# view_static/ 与 test_chain_plan_cases.js 用模板自有风格（2 空格/单引号），
# package.json / sync_state.json 缩进随消费仓 tabWidth 漂移（sync_state.json 每轮 apply 重写），
# tasks_index.json 系派生索引（store.py 写 indent=4，可重建），handoff.json 由 task 流程逐任务生成，
# .opencode/package*.json 属本地生成（prettier 不认嵌套 .gitignore）。
# 由 merge_prettierignore 机械追加，消费独有规则保留。
PRETTIERIGNORE_TEMPLATE_RULES = (
    ".repo_template/scripts/package.json",
    ".repo_template/tests/package.json",
    ".repo_template/scripts/repo_task/view_static/",
    ".repo_template/tests/test_chain_plan_cases.js",
    ".repo_template/sync_state.json",
    "docs/tasks_index.json",
    "docs/archive/tasks_index.json",
    "docs/**/handoff.json",
    ".opencode/package.json",
    ".opencode/package-lock.json",
)

# 已下线模板产物：b3e5c8f 起不再分发，残留消费仓时只警告不自动删（防丢消费定制）。
RETIRED_TEMPLATE_PATHS = (".github/workflows/repo-template-ci.yml",)


class SyncError(Exception):
    pass


def _git(repo: Path, *args: str) -> subprocess.CompletedProcess:
    return subprocess.run(
        ["git", "-C", str(repo), *args],
        capture_output=True, text=True, encoding="utf-8", errors="replace",
        timeout=30,
    )


def _rel(path: Path) -> str:
    return path.relative_to(CONSUMER).as_posix()


def _is_noise(name: str) -> bool:
    return name in NOISE_NAMES or name in PROTECT_NAMES or name.endswith(".pyc")


# apply 中途失败的回滚栈：备份被覆盖/删除目标的旧内容到独立回滚目录，OSError 时恢复（F16）。
# 备份放 .scratch/（gitignore、不在同步树内），避免 sync_dir 的删除 pass 把备份当漂移删掉。
# _ROLLBACK_DIR 动态求值：CONSUMER 可能被测试/调用方 monkeypatch。
_ROLLBACK: list[tuple[Path, Path | None]] = []  # (目标路径, 备份路径)；None = 原不存在


def _rollback_dir() -> Path:
    return CONSUMER / ".scratch" / "repo_sync_rollback"


def _stage_rollback(path: Path) -> None:
    """记录被覆盖/删除目标。文件/目录/软链复制到回滚目录（含相对路径），原样保留原路径。"""
    if path.exists() or path.is_symlink():
        rel = _rel(path)
        backup = _rollback_dir() / rel
        if path.is_dir() and not path.is_symlink():
            backup.parent.mkdir(parents=True, exist_ok=True)
            if backup.exists():
                shutil.rmtree(backup, ignore_errors=True)
            shutil.copytree(path, backup)
        else:
            backup.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(path, backup, follow_symlinks=False)
        _ROLLBACK.append((path, backup))
    else:
        _ROLLBACK.append((path, None))


def _rollback_changes() -> None:
    for path, backup in reversed(_ROLLBACK):
        try:
            if backup is None:
                # 原不存在：删除 apply 创建的
                if path.is_dir() and not path.is_symlink():
                    shutil.rmtree(path, ignore_errors=True)
                else:
                    path.unlink(missing_ok=True)
            else:
                # 移除 apply 写入的，再从备份恢复
                if path.is_dir() and not path.is_symlink():
                    shutil.rmtree(path, ignore_errors=True)
                elif path.is_symlink() or path.exists():
                    path.unlink(missing_ok=True)
                path.parent.mkdir(parents=True, exist_ok=True)
                backup.replace(path)
        except OSError:
            pass


def _cleanup_rollback() -> None:
    rollback_dir = _rollback_dir()
    if rollback_dir.exists():
        shutil.rmtree(rollback_dir, ignore_errors=True)


def _file_differs(a: Path, b: Path) -> bool:
    if a.is_symlink() or b.is_symlink():
        return a.resolve() != b.resolve()
    if a.stat().st_size != b.stat().st_size:
        return True
    return a.read_bytes() != b.read_bytes()


# ---------------------------------------------------------------------------
# sync_state.json 读写（字段级原子更新纪律）
# ---------------------------------------------------------------------------

def read_state() -> dict | None:
    if not STATE_PATH.exists():
        return None
    with open(STATE_PATH, encoding="utf-8") as f:
        return json.load(f)


def write_state(data: dict) -> None:
    STATE_PATH.parent.mkdir(parents=True, exist_ok=True)
    tmp = STATE_PATH.with_name(STATE_PATH.name + ".tmp")
    with open(tmp, "w", encoding="utf-8", newline="\n") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
        f.write("\n")
    tmp.replace(STATE_PATH)


def active_prompts(state: dict | None) -> list[dict]:
    """返回未 revoked 的 user_prompts 条目。"""
    if not state:
        return []
    return [p for p in state.get("user_prompts", []) if not p.get("revoked")]


def prompt_substrings(state: dict | None) -> list[str]:
    """从活跃 prompt 的 tags 提取拦截子串（供 .gitignore 规则匹配）。"""
    out: list[str] = []
    for p in active_prompts(state):
        for tag in p.get("tags", []):
            t = str(tag).strip()
            if t and t not in out:
                out.append(t)
    return out


def resolve_src(state: dict | None) -> Path:
    if not state or not state.get("template_source", {}).get("value"):
        raise SyncError("未初始化：缺少 template_source。先运行 init --source <path|url>")
    ts = state["template_source"]
    kind = ts.get("kind", "path")
    value = ts["value"]
    if kind == "url":
        cache = CONSUMER / ".scratch/repo_template_sync_src"
        if not (cache / ".git").exists():
            cache.parent.mkdir(parents=True, exist_ok=True)
            r = _git(cache.parent, "clone", value, cache.name)
            if r.returncode != 0:
                raise SyncError(f"clone 模板源失败：{r.stderr.strip()}")
        else:
            r = _git(cache, "pull", "--ff-only")
            if r.returncode != 0:
                raise SyncError(f"更新模板源失败：{r.stderr.strip()}")
        src = cache.resolve()
    else:
        src = Path(value).expanduser().resolve()
    return _as_product(src)


def _as_product(src: Path) -> Path:
    """接受产物根，或工厂仓根（内含 repo/）。"""
    if (src / PRODUCT_MARKER).is_file():
        return src
    nested = src / "repo"
    if (nested / PRODUCT_MARKER).is_file():
        return nested
    raise SyncError(f"模板源无效：{src} 不含 {PRODUCT_MARKER}（也不是含 repo/ 的工厂根）")


def assert_not_self(src: Path) -> None:
    if src == CONSUMER:
        raise SyncError("当前仓库与 template_source 同一路径，禁止在模板仓当推送源同步")


# ---------------------------------------------------------------------------
# Workflow schema migration (forced on apply)
# ---------------------------------------------------------------------------

_GUIDE_OPEN = "<!-- 规范（门禁必留，不得删除） -->"
_GUIDE_CLOSE = "<!-- /规范 -->"
_OLD_NOTE_PREFIXES = (
    "执行期边做边写：",
    "创建期不预测实施步骤——",
    "执行期记录关键步骤、决策、验证、阻塞和用户批准的新轮次上限。",
    "创建期不预测实施步骤。只记有追溯价值的内容；无事项时写“无”。",
)


def _guide_blocks_by_heading(text: str) -> dict[str, list[str]]:
    heading = ""
    blocks: dict[str, list[str]] = {}
    lines = text.splitlines()
    index = 0
    while index < len(lines):
        line = lines[index]
        if line.startswith("### "):
            heading = line[4:].strip()
        if line.strip() == _GUIDE_OPEN:
            block = [line]
            index += 1
            while index < len(lines):
                block.append(lines[index])
                if lines[index].strip() == _GUIDE_CLOSE:
                    break
                index += 1
            if not block or block[-1].strip() != _GUIDE_CLOSE:
                raise SyncError("当前 spec 模板规范块未闭合")
            blocks.setdefault(heading, []).append("\n".join(block))
        index += 1
    return blocks


def _replace_guide_blocks(text: str, current_template: str) -> str:
    current = _guide_blocks_by_heading(current_template)
    if not current:
        return text
    lines = text.splitlines()
    output: list[str] = []
    index = 0
    while index < len(lines):
        stripped = lines[index].strip()
        if not stripped.startswith("### "):
            output.append(lines[index])
            index += 1
            continue
        heading = stripped[4:].strip()
        end = index + 1
        while end < len(lines):
            marker = lines[end].strip()
            if marker.startswith("### ") or marker.startswith("## "):
                break
            end += 1
        section = lines[index:end]
        content: list[str] = []
        cursor = 1
        old_block_count = 0
        while cursor < len(section):
            if section[cursor].strip() != _GUIDE_OPEN:
                content.append(section[cursor])
                cursor += 1
                continue
            old_block_count += 1
            cursor += 1
            while cursor < len(section) and section[cursor].strip() != _GUIDE_CLOSE:
                cursor += 1
            if cursor >= len(section):
                raise SyncError(f"存量 spec 的 {heading!r} 规范块未闭合，拒绝猜测迁移")
            cursor += 1
        replacements = current.get(heading, [])
        if not replacements and old_block_count == 0:
            output.extend(section)
            index = end
            continue
        while content and not content[0].strip():
            content.pop(0)
        while content and not content[-1].strip():
            content.pop()
        rendered: list[str] = [section[0], ""]
        for block_index, block in enumerate(replacements):
            if block_index:
                rendered.append("")
            rendered.extend(block.splitlines())
        if replacements and content:
            rendered.append("")
        rendered.extend(content)
        rendered.append("")
        output.extend(rendered)
        index = end
    return "\n".join(output).rstrip() + "\n"


def _implementation_guidance(task_template: str) -> list[str]:
    lines = task_template.splitlines()
    start = next(
        (index + 1 for index, line in enumerate(lines) if line.strip() == "## 实施笔记"),
        None,
    )
    if start is None:
        return []
    section = []
    for line in lines[start:]:
        if line.startswith("## "):
            break
        if line.strip() and line.strip() != "无":
            section.append(line.strip())
        if len(section) == 2:
            break
    return section


def _migrate_task_text(text: str, task_template: str) -> str:
    lines = text.splitlines()
    migrated = []
    has_review = False
    has_verify = False
    in_frontmatter = False
    frontmatter_end = 0
    for index, line in enumerate(lines):
        if index == 0 and line.strip() == "---":
            in_frontmatter = True
        elif in_frontmatter and line.strip() == "---":
            frontmatter_end = index
            in_frontmatter = False
        elif in_frontmatter:
            key = line.partition(":")[0].strip()
            if key == "schedule_status":
                continue
            has_review = has_review or bool(re.match(r'^review_limit\s*:', line))
            has_verify = has_verify or bool(re.match(r'^verify_limit\s*:', line))
            if re.match(r'^status\s*:\s*["\']?blocked["\']?\s*$', line):
                line = 'status: "active"'
        migrated.append(line)

    guidance = _implementation_guidance(task_template)
    section_start = next(
        (index + 1 for index, line in enumerate(migrated) if line.strip() == "## 实施笔记"),
        None,
    )
    if section_start is not None and guidance:
        section_end = next(
            (i for i in range(section_start, len(migrated)) if migrated[i].startswith("## ")),
            len(migrated),
        )
        content = [
            line for line in migrated[section_start:section_end]
            if not any(line.strip().startswith(prefix) for prefix in _OLD_NOTE_PREFIXES)
        ]
        while content and not content[0].strip():
            content.pop(0)
        migrated[section_start:section_end] = [
            "", guidance[0], "", *guidance[1:], "", *content,
        ]
    if frontmatter_end and (not has_review or not has_verify):
        close = next(i for i in range(1, len(migrated)) if migrated[i].strip() == "---")
        fields = []
        if not has_review:
            fields.append('review_limit: "5"')
        if not has_verify:
            fields.append('verify_limit: "5"')
        migrated[close:close] = fields
    return "\n".join(migrated).rstrip() + "\n"


def _registered_task_worktrees() -> list[tuple[Path, str]]:
    result = _git(CONSUMER, "worktree", "list", "--porcelain")
    if result.returncode != 0:
        return []
    rows: list[tuple[Path, str]] = []
    root: Path | None = None
    for raw in result.stdout.splitlines() + [""]:
        if raw.startswith("worktree "):
            root = Path(raw.removeprefix("worktree ")).resolve()
        elif raw.startswith("branch refs/heads/") and root is not None:
            branch = raw.removeprefix("branch refs/heads/")
            if root != CONSUMER.resolve() and re.match(r"^t[0-9]+_", branch):
                rows.append((root, branch))
        elif not raw:
            root = None
    return rows

def workflow_migration_status(
    src: Path,
) -> tuple[list[str], list[tuple[Path, str]], list[str]]:
    spec_path = src / ".repo_template/docs/task_template/spec.md"
    task_path = src / ".repo_template/docs/task_template/task.md"
    worktrees = _registered_task_worktrees()
    if not spec_path.is_file() or not task_path.is_file():
        return [], worktrees, []
    spec_template = spec_path.read_text(encoding="utf-8")
    task_template = task_path.read_text(encoding="utf-8")
    if not _guide_blocks_by_heading(spec_template) or "## 实施笔记" not in task_template:
        return [], worktrees, []
    candidates: list[str] = []
    errors: list[str] = []
    tasks_dir = CONSUMER / "docs/tasks"
    if tasks_dir.is_dir():
        for task_dir in tasks_dir.glob("t[0-9]*_*"):
            if not task_dir.is_dir():
                continue
            for filename, transform in (
                ("spec.md", lambda text: _replace_guide_blocks(text, spec_template)),
                ("task.md", lambda text: _migrate_task_text(text, task_template)),
            ):
                path = task_dir / filename
                if not path.is_file():
                    continue
                before = path.read_text(encoding="utf-8")
                try:
                    after = transform(before)
                except SyncError as error:
                    errors.append(f"{_rel(path)}: {error}")
                    continue
                if after != before:
                    candidates.append(_rel(path))
    return sorted(candidates), worktrees, sorted(errors)


def force_migrate_workflow_tasks(changed: set[Path]) -> list[str]:
    spec_template_path = CONSUMER / ".repo_template/docs/task_template/spec.md"
    task_template_path = CONSUMER / ".repo_template/docs/task_template/task.md"
    if not spec_template_path.is_file() or not task_template_path.is_file():
        return []
    spec_template = spec_template_path.read_text(encoding="utf-8")
    task_template = task_template_path.read_text(encoding="utf-8")
    if not _guide_blocks_by_heading(spec_template) or "## 实施笔记" not in task_template:
        return []
    registered = _registered_task_worktrees()
    if registered:
        detail = ", ".join(f"{branch}@{root}" for root, branch in registered)
        raise SyncError(
            "workflow schema 强制更新前必须先完成或 rewind 已登记 task worktree：" + detail
        )
    planned: list[tuple[Path, str]] = []
    errors: list[str] = []
    tasks_dir = CONSUMER / "docs/tasks"
    if not tasks_dir.is_dir():
        return []
    for task_dir in tasks_dir.glob("t[0-9]*_*"):
        if task_dir.name == "task_template" or not task_dir.is_dir():
            continue
        for filename, transform in (
            ("spec.md", lambda text: _replace_guide_blocks(text, spec_template)),
            ("task.md", lambda text: _migrate_task_text(text, task_template)),
        ):
            path = task_dir / filename
            if not path.is_file():
                continue
            before = path.read_text(encoding="utf-8")
            try:
                after = transform(before)
            except SyncError as error:
                errors.append(f"{_rel(path)}: {error}")
                continue
            if after != before:
                planned.append((path, after))
    if errors:
        raise SyncError("workflow schema 无法安全迁移：" + "；".join(errors))
    reports = []
    for path, after in planned:
        _stage_rollback(path)
        path.write_text(after, encoding="utf-8")
        changed.add(path)
        reports.append(f"{_rel(path)} 已强制迁移到当前 workflow schema")
    return reports


# ---------------------------------------------------------------------------
# 硬同步（树对树 / 单文件）
# ---------------------------------------------------------------------------

def sync_dir(src_dir: Path, dst_dir: Path, changed: set[Path]) -> None:
    """树对树同步：src 全量复制（含覆盖），dst 中 src 没有的非噪声条目删除。"""
    if not dst_dir.exists():
        dst_dir.mkdir(parents=True)
    for entry in src_dir.iterdir():
        if _is_noise(entry.name):
            continue
        target = dst_dir / entry.name
        if entry.is_dir():
            sync_dir(entry, target, changed)
        else:
            if not target.exists() or _file_differs(entry, target):
                _stage_rollback(target)
                shutil.copy2(entry, target)
                changed.add(target)
    for entry in dst_dir.iterdir():
        if _is_noise(entry.name):
            continue
        if not (src_dir / entry.name).exists():
            _stage_rollback(entry)
            if entry.is_dir() and not entry.is_symlink():
                shutil.rmtree(entry)
            else:
                entry.unlink()
            changed.add(entry)


def sync_dir_oneway(src_dir: Path, dst_dir: Path, changed: set[Path]) -> None:
    """单向树同步：src 全量复制（含覆盖），不删 dst 中 src 没有的条目。"""
    if not src_dir.exists():
        return
    if not dst_dir.exists():
        dst_dir.mkdir(parents=True)
    for entry in src_dir.iterdir():
        if _is_noise(entry.name):
            continue
        target = dst_dir / entry.name
        if entry.is_dir():
            sync_dir_oneway(entry, target, changed)
        else:
            if not target.exists() or _file_differs(entry, target):
                _stage_rollback(target)
                shutil.copy2(entry, target)
                changed.add(target)


def sync_file(src: Path, dst: Path, changed: set[Path]) -> None:
    """单文件：src 有 → 拷贝（相同则不动）；src 无 → 删 dst。"""
    if not src.exists():
        if dst.exists():
            _stage_rollback(dst)
            dst.unlink()
            changed.add(dst)
        return
    if not dst.exists() or _file_differs(src, dst):
        dst.parent.mkdir(parents=True, exist_ok=True)
        _stage_rollback(dst)
        shutil.copy2(src, dst)
        changed.add(dst)


# ---------------------------------------------------------------------------
# skill 整目录覆盖 + 软链
# ---------------------------------------------------------------------------

def sync_skill(src_skill: Path, dst_skill: Path, changed: set[Path]) -> None:
    """整 skill 目录覆盖（含 front matter），保护 sync_state.json，不做 --delete。"""
    if not dst_skill.exists():
        dst_skill.mkdir(parents=True)
    for entry in src_skill.iterdir():
        if entry.name == "sync_state.json":
            continue
        target = dst_skill / entry.name
        if entry.is_dir():
            sync_dir(entry, target, changed)
        else:
            if not target.exists() or _file_differs(entry, target):
                _stage_rollback(target)
                shutil.copy2(entry, target)
                changed.add(target)


def _ensure_symlink(link: Path, target_rel: str, expected: Path, changed: set[Path], reports: list[str]) -> None:
    if link.is_symlink():
        if link.resolve() == expected:
            return
        _stage_rollback(link)
        link.unlink()
        os.symlink(target_rel, link)
        changed.add(link)
        return
    if link.is_dir():
        # 旧架构残留：宿主位曾是模板同步进去的真实目录。新架构真相源收敛到
        # .repo_template/skills/，宿主位只留软链。备份旧内容后转软链。
        _stage_rollback(link)
        shutil.rmtree(link)
        os.symlink(target_rel, link)
        changed.add(link)
        reports.append(f"{_rel(link)} 旧真实目录已转软链（原内容入回滚栈）")
        return
    if link.exists():
        reports.append(f"{_rel(link)} 非本机制管理，跳过")
        return
    link.parent.mkdir(parents=True, exist_ok=True)
    os.symlink(target_rel, link)
    changed.add(link)


_RETIRED_MERGE_GUARD_COMMAND = 'python3 "$CLAUDE_PROJECT_DIR/.claude/hooks/merge_guard.py"'


def _detect_json_indent(raw: str) -> int | str:
    """从现有 JSON 文本推断缩进（首个 ^(空格|tab)+\" 行），无匹配回退 2。

    同步改写消费仓 JSON（settings.json / MCP）时沿用原缩进，避免把消费仓
    4 空格体例重排成 2 空格、反而弄红其 prettier 门禁。
    """
    for line in raw.splitlines():
        if not line or line[0] not in (" ", "\t"):
            continue
        stripped = line.lstrip(" \t")
        if stripped.startswith('"'):
            prefix = line[: len(line) - len(stripped)]
            if set(prefix) == {"\t"}:
                return "\t"
            if set(prefix) == {" "}:
                return len(prefix)
    return 2


def _remove_retired_merge_guard_setting(changed: set[Path], reports: list[str]) -> None:
    settings = CONSUMER / ".claude/settings.json"
    if not settings.is_file():
        return
    try:
        raw = settings.read_text(encoding="utf-8")
        data = json.loads(raw)
    except (json.JSONDecodeError, UnicodeDecodeError, OSError) as error:
        raise SyncError(
            f"{_rel(settings)} 无法解析，不能安全移除已退役 merge guard PreToolUse（{error}）"
        ) from error
    hooks = data.get("hooks")
    if not isinstance(hooks, dict):
        return
    groups = hooks.get("PreToolUse")
    if not isinstance(groups, list):
        return
    changed_settings = False
    kept_groups = []
    for group in groups:
        if not isinstance(group, dict):
            kept_groups.append(group)
            continue
        entries = group.get("hooks")
        if not isinstance(entries, list):
            kept_groups.append(group)
            continue
        kept_entries = [
            entry for entry in entries
            if not (
                isinstance(entry, dict)
                and str(entry.get("command", "")).strip() == _RETIRED_MERGE_GUARD_COMMAND
            )
        ]
        if len(kept_entries) != len(entries):
            changed_settings = True
        if kept_entries:
            updated = dict(group)
            updated["hooks"] = kept_entries
            kept_groups.append(updated)
    if not changed_settings:
        return
    _stage_rollback(settings)
    if kept_groups:
        hooks["PreToolUse"] = kept_groups
    else:
        hooks.pop("PreToolUse", None)
    if not hooks:
        data.pop("hooks", None)
    temporary = settings.with_name(settings.name + ".tmp")
    temporary.write_text(json.dumps(data, ensure_ascii=False, indent=_detect_json_indent(raw)) + "\n", encoding="utf-8")
    temporary.replace(settings)
    changed.add(settings)
    reports.append(f"{_rel(settings)} 已移除退役 merge guard PreToolUse")


def repair_symlinks(changed: set[Path]) -> list[str]:
    """建/修宿主软链，指向 .repo_template/。非本机制链接报告不碰。"""
    reports: list[str] = []
    if SKILLS_SRC.exists():
        for entry in SKILLS_SRC.iterdir():
            if not entry.is_dir():
                continue
            expected = entry.resolve()
            _ensure_symlink(
                SKILLS_CLAUDE / entry.name,
                os.path.join("..", "..", ".repo_template", "skills", entry.name),
                expected, changed, reports,
            )
            _ensure_symlink(
                SKILLS_AGENTS / entry.name,
                os.path.join("..", "..", ".repo_template", "skills", entry.name),
                expected, changed, reports,
            )
    legacy_guard = CONSUMER / ".claude/hooks/merge_guard.py"
    retired_target = CONSUMER / ".repo_template/hooks/merge_guard.py"
    managed_retired_guard = (
        legacy_guard.is_symlink()
        and legacy_guard.resolve(strict=False) == retired_target.resolve(strict=False)
    )
    guard_missing = not legacy_guard.exists() and not legacy_guard.is_symlink()
    if managed_retired_guard or guard_missing:
        _remove_retired_merge_guard_setting(changed, reports)
    if managed_retired_guard:
        _stage_rollback(legacy_guard)
        legacy_guard.unlink()
        changed.add(legacy_guard)
        reports.append(f"{_rel(legacy_guard)} 已退役并移除")
    return reports


def _skill_description(skill_dir: Path, name: str) -> str:
    """读 SKILL.md frontmatter 的 description；缺失/无意义时回退。"""
    desc = f"Run {name} skill"
    try:
        text = (skill_dir / "SKILL.md").read_text(encoding="utf-8")
    except OSError:
        return desc
    if text.startswith("---"):
        end = text.find("---", 3)
        if end != -1:
            for line in text[3:end].splitlines():
                if line.startswith("description:"):
                    desc = line.split(":", 1)[1].strip()
                    break
    if not desc or desc.lower() == "none":
        desc = f"Run {name} skill"
    return desc.replace('"', "'")


def sync_opencode_commands(changed: set[Path]) -> list[str]:
    """项目级 opencode 命令薄层：每个 skill 生成同名 /<skill> 命令。

    opencode 能直接识别 .agents/skills，但缺 / 触发器。命令正文只做一件事：
    让 agent 经 skill 工具加载执行对应 skill，$ARGUMENTS 透传。description
    取自 SKILL.md frontmatter（SKILL.md 是唯一真相源）。
    手写命令（无本机制标记）永不覆盖/删除；skill 删除后仅清理带标记残留。
    """
    reports: list[str] = []
    if not SKILLS_SRC.exists():
        return reports
    COMMANDS_OPENCODE.mkdir(parents=True, exist_ok=True)
    names = sorted(e.name for e in SKILLS_SRC.iterdir() if e.is_dir())
    for name in names:
        content = (
            "---\n"
            f'description: "{_skill_description(SKILLS_SRC / name, name)}"\n'
            "---\n"
            f"> {COMMAND_MARKER} '{name}'. Do not edit directly.\n\n"
            f"Load and execute the `{name}` skill via the `skill` tool, "
            "following its SKILL.md instructions.\n\n"
            "User arguments: $ARGUMENTS\n"
        )
        dest = COMMANDS_OPENCODE / f"{name}.md"
        if dest.exists() and not dest.is_file():
            continue
        if dest.is_file():
            existing = dest.read_text(encoding="utf-8")
            if existing == content:
                continue
            if COMMAND_MARKER not in existing:
                reports.append(f"{_rel(dest)} 疑似手写命令（与 skill 同名），跳过")
                continue
        _stage_rollback(dest)
        dest.write_text(content, encoding="utf-8")
        changed.add(dest)
    for md in COMMANDS_OPENCODE.glob("*.md"):
        if md.stem in names:
            continue
        try:
            if COMMAND_MARKER in md.read_text(encoding="utf-8"):
                _stage_rollback(md)
                md.unlink()
                changed.add(md)
        except OSError:
            continue
    return reports


# ---------------------------------------------------------------------------
# 差异扫描
# ---------------------------------------------------------------------------

def _dir_has_diff(src_dir: Path, dst_dir: Path) -> bool:
    """目录树是否存在实质差异（非噪声）。"""
    if not src_dir.exists() and not dst_dir.exists():
        return False
    if src_dir.exists() != dst_dir.exists():
        return True
    src_files = {p.relative_to(src_dir) for p in src_dir.rglob("*")
                 if p.is_file() and not any(_is_noise(part) for part in p.relative_to(src_dir).parts)}
    dst_files = {p.relative_to(dst_dir) for p in dst_dir.rglob("*")
                 if p.is_file() and not any(_is_noise(part) for part in p.relative_to(dst_dir).parts)}
    if src_files != dst_files:
        return True
    for rel in src_files:
        if _file_differs(src_dir / rel, dst_dir / rel):
            return True
    return False


def hard_sync_status(src: Path) -> list[dict]:
    """硬同步清单状态：write / delete / same。"""
    out: list[dict] = []
    for rel in HARD_SYNC_DIRS:
        s, d = src / rel, CONSUMER / rel
        if not s.exists() and not d.exists():
            continue
        if not s.exists():
            out.append({"rel": rel + "/", "state": "delete"})
        elif not d.exists() or _dir_has_diff(s, d):
            out.append({"rel": rel + "/", "state": "write"})
        else:
            out.append({"rel": rel + "/", "state": "same"})
    for rel in HARD_SYNC_FILES:
        s, d = src / rel, CONSUMER / rel
        if not s.exists() and not d.exists():
            continue
        if not s.exists():
            out.append({"rel": rel, "state": "delete"})
        elif not d.exists() or _file_differs(s, d):
            out.append({"rel": rel, "state": "write"})
        else:
            out.append({"rel": rel, "state": "same"})
    return out


def skill_status(src: Path) -> list[dict]:
    """skill 状态：模板侧 override；消费侧独有 keep；旧真实目录 stale。"""
    out: list[dict] = []
    src_skills = src / ".repo_template/skills"
    if src_skills.exists():
        for s in src_skills.iterdir():
            if s.is_dir():
                d = SKILLS_SRC / s.name
                diff = not d.exists() or _dir_has_diff(s, d)
                out.append({"name": s.name, "action": "override" if diff else "same"})
    if SKILLS_AGENTS.exists():
        for d in SKILLS_AGENTS.iterdir():
            if not d.is_dir():
                continue
            if d.is_symlink():
                continue
            if src_skills.exists() and (src_skills / d.name).exists():
                out.append({"name": d.name, "action": "stale"})
                continue
            out.append({"name": d.name, "action": "keep"})
    return out


def symlink_status() -> list[dict]:
    out: list[dict] = []
    if not SKILLS_SRC.exists():
        return out
    for entry in SKILLS_SRC.iterdir():
        if not entry.is_dir():
            continue
        link = SKILLS_CLAUDE / entry.name
        if link.is_symlink() and link.resolve() == entry.resolve():
            out.append({"name": entry.name, "state": "ok"})
        elif link.exists() and not link.is_symlink():
            out.append({"name": entry.name, "state": "unmanaged"})
        else:
            out.append({"name": entry.name, "state": "repair"})
    return out


def shared_class(src_path: Path, dst_path: Path) -> str:
    if src_path.exists() and not dst_path.exists():
        return "template_only"
    if dst_path.exists() and not src_path.exists():
        return "consumer_only"
    if src_path.exists() and dst_path.exists():
        if _file_differs(src_path, dst_path):
            return "both_differ"
        return "both_identical"
    return "none"


def shared_status(src: Path) -> list[dict]:
    """裁定单元分类（AGENTS.md 处理 CLAUDE.md 软链实体）。"""
    out: list[dict] = []
    for unit in SHARED_FILES:
        s = src / unit
        if unit == "AGENTS.md":
            d = CONSUMER / "AGENTS.md"
            if d.is_symlink():
                d = d.resolve()
        else:
            d = CONSUMER / unit
        out.append({"unit": unit, "cls": shared_class(s, d)})
    return out


def src_dirty(src: Path) -> bool:
    paths = list(HARD_SYNC_DIRS) + list(HARD_SYNC_FILES) + list(SHARED_FILES)
    r = _git(src, "status", "--porcelain", "--", *paths)
    if r.returncode != 0:
        # git 失败时按 dirty 处理并打 WARNING，避免误推进 last_synced_commit（F36）
        print(
            f"WARNING: 无法判断模板源是否干净（{r.stderr.strip()}）；按 dirty 处理",
            file=sys.stderr,
        )
        return True
    return bool(r.stdout.strip())


# ---------------------------------------------------------------------------
# 机械合并（.gitignore / MCP）
# ---------------------------------------------------------------------------

def _blocked(rule: str, substrings: list[str]) -> bool:
    return any(sub in rule for sub in substrings)


def merge_gitignore(src: Path, blocked: list[str], changed: set[Path]) -> dict:
    """追加模板独有规则（去重、遵从 prompt 拦截）；删除消费侧 prompt 禁止的 ignore 行。"""
    dst = CONSUMER / ".gitignore"
    src_lines = (src / ".gitignore").read_text(encoding="utf-8").splitlines()
    dst_lines = dst.read_text(encoding="utf-8").splitlines() if dst.exists() else []
    dst_set = {ln.strip() for ln in dst_lines}
    added: list[str] = []
    removed: list[str] = []
    for ln in src_lines:
        stripped = ln.strip()
        if not stripped or stripped.startswith("#"):
            continue
        if stripped in dst_set:
            continue
        if _blocked(stripped, blocked):
            continue
        added.append(stripped)
    if blocked:
        new_dst: list[str] = []
        for ln in dst_lines:
            stripped = ln.strip()
            if stripped and not stripped.startswith("#") and _blocked(stripped, blocked):
                removed.append(stripped)
                continue
            new_dst.append(ln)
        dst_lines = new_dst
    if added or removed:
        if added:
            dst_lines.append("")
            dst_lines.append("# 同步自模板（repo-template-sync）")
            dst_lines.extend(added)
        text = "\n".join(dst_lines)
        if not text.endswith("\n"):
            text += "\n"
        dst.parent.mkdir(parents=True, exist_ok=True)
        _stage_rollback(dst)
        dst.write_text(text, encoding="utf-8", newline="\n")
        changed.add(dst)
    return {"added": added, "removed": removed, "dst": _rel(dst)}


def merge_prettierignore(changed: set[Path]) -> dict:
    """机械合并 .prettierignore：模板自有路径去重追加，消费独有规则保留。"""
    dst = CONSUMER / ".prettierignore"
    dst_lines = dst.read_text(encoding="utf-8").splitlines() if dst.exists() else []
    dst_set = {ln.strip() for ln in dst_lines}
    added: list[str] = []
    for rule in PRETTIERIGNORE_TEMPLATE_RULES:
        if rule not in dst_set:
            added.append(rule)
    if added:
        if dst_lines and dst_lines[-1].strip():
            dst_lines.append("")
        dst_lines.append("# 同步自模板（repo-template-sync）：模板自有路径不受消费仓 format 门禁约束")
        dst_lines.extend(added)
        text = "\n".join(dst_lines)
        if not text.endswith("\n"):
            text += "\n"
        dst.parent.mkdir(parents=True, exist_ok=True)
        _stage_rollback(dst)
        dst.write_text(text, encoding="utf-8", newline="\n")
        changed.add(dst)
    return {"added": added, "dst": _rel(dst)}


def retired_template_warnings() -> list[str]:
    """已下线模板产物残留提醒：只读检查，不写盘。"""
    warnings = []
    for rel in RETIRED_TEMPLATE_PATHS:
        if (CONSUMER / rel).exists():
            warnings.append(
                f"{rel} 为已下线模板产物（b3e5c8f 起不再分发），"
                "确认无消费定制后手动删除，否则消费仓 format 门禁持续报红"
            )
    return warnings


def merge_mcp(src: Path, changed: set[Path]) -> list[str]:
    """按 server 键合并 MCP：模板新增键加入，已有键保留消费值（禁冲密钥）。"""
    merged: list[str] = []
    for rel in MCP_CANDIDATES:
        sp, dp = src / rel, CONSUMER / rel
        if not sp.exists():
            continue
        try:
            sdata = json.loads(sp.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError) as e:
            print(f"WARNING: 模板侧 {rel} 无法解析，跳过 MCP 合并（{e}）", file=sys.stderr)
            continue
        if not dp.exists():
            dp.parent.mkdir(parents=True, exist_ok=True)
            _stage_rollback(dp)
            shutil.copy2(sp, dp)
            changed.add(dp)
            merged.append(_rel(dp))
            continue
        try:
            draw = dp.read_text(encoding="utf-8")
            ddata = json.loads(draw)
        except (OSError, json.JSONDecodeError) as e:
            print(f"WARNING: 消费侧 {rel} 无法解析，跳过 MCP 合并（{e}）", file=sys.stderr)
            continue
        dservers = ddata.setdefault("mcpServers", {})
        touched = False
        for key, val in sdata.get("mcpServers", {}).items():
            if key not in dservers:
                dservers[key] = val
                touched = True
        if touched:
            _stage_rollback(dp)
            dp.write_text(json.dumps(ddata, ensure_ascii=False, indent=_detect_json_indent(draw)) + "\n",
                          encoding="utf-8", newline="\n")
            changed.add(dp)
            merged.append(_rel(dp))
    return merged


# ---------------------------------------------------------------------------
# apply 组装
# ---------------------------------------------------------------------------

def _markdown_section(text: str, heading: str) -> tuple[int, int, str] | None:
    """返回 heading 所在 section 的 (start, end, text)，section 结束于下一个同级标题。"""
    lines = text.splitlines(keepends=True)
    offsets: list[tuple[int, str]] = []
    offset = 0
    for line in lines:
        if line.startswith("## "):
            offsets.append((offset, line.strip()))
        offset += len(line)
    for index, (start, title) in enumerate(offsets):
        if title != heading:
            continue
        end = offsets[index + 1][0] if index + 1 < len(offsets) else len(text)
        return start, end, text[start:end]
    return None


def _agents_parts(text: str) -> dict[str, tuple[int, int, str]]:
    """识别 AGENTS.md 的 intro、merge、force 三部分；缺少强制标题则拒绝同步。"""
    merge = _markdown_section(text, AGENTS_MERGE_HEADING)
    force = _markdown_section(text, AGENTS_FORCE_HEADING)
    if merge is None or force is None:
        raise SyncError("AGENTS.md 缺少 ## 目录与读写规则 或 ## 开发原则，拒绝猜测同步")
    intro_end = merge[0]
    return {"intro": (0, intro_end, text[:intro_end]), "merge": merge, "force": force}


def _replace_agents_force(src_text: str, dst_text: str) -> tuple[str, bool, bool, bool]:
    """仅替换开发原则；返回新文本、force 是否变化、merge 是否不同、intro 是否不同。"""
    src_parts = _agents_parts(src_text)
    dst_parts = _agents_parts(dst_text)
    src_force = src_parts["force"]
    dst_force = dst_parts["force"]
    result = dst_text[:dst_force[0]] + src_text[src_force[0]:src_force[1]] + dst_text[dst_force[1]:]
    return (
        result,
        result != dst_text,
        src_parts["merge"][2] != dst_parts["merge"][2],
        src_parts["intro"][2] != dst_parts["intro"][2],
    )


def agents_section_status(src: Path) -> dict[str, str] | None:
    sp, dp = src / "AGENTS.md", CONSUMER / "AGENTS.md"
    if not sp.exists() or not dp.exists():
        return None
    src_parts = _agents_parts(sp.read_text(encoding="utf-8"))
    dst_path = dp.resolve() if dp.is_symlink() else dp
    dst_parts = _agents_parts(dst_path.read_text(encoding="utf-8"))
    return {
        "intro": "protected" if src_parts["intro"][2] != dst_parts["intro"][2] else "same",
        "merge": "different" if src_parts["merge"][2] != dst_parts["merge"][2] else "same",
        "force": "different" if src_parts["force"][2] != dst_parts["force"][2] else "same",
    }


def _apply_agents_sectioned(src: Path, changed: set[Path]) -> bool:
    sp, dp = src / "AGENTS.md", CONSUMER / "AGENTS.md"
    if not sp.exists():
        return False
    src_text = sp.read_text(encoding="utf-8")
    # 旧版模板源没有固定标题时，交回旧的整文件裁定逻辑。
    try:
        _agents_parts(src_text)
    except SyncError:
        return False
    if not dp.exists():
        raise SyncError("模板 AGENTS.md 已启用分区协议，但消费仓缺少 AGENTS.md")
    target = dp.resolve() if dp.is_symlink() else dp
    dst_text = target.read_text(encoding="utf-8")
    result, force_changed, merge_diff, intro_diff = _replace_agents_force(src_text, dst_text)
    if intro_diff:
        print("提示: AGENTS.md 项目介绍与模板不同；按规则保护消费仓内容，不覆盖")
    if merge_diff:
        print("提示: AGENTS.md 目录与读写规则与模板不同；交由 agent 语义合并，脚本不覆盖")
    if force_changed:
        _stage_rollback(target)
        target.write_text(result, encoding="utf-8", newline="\n")
        changed.add(target)
    return True

def _apply_shared_unit(unit: str, decision: str | None, src: Path, changed: set[Path]) -> None:
    # 标题协议下只自动更新开发原则；其余部分分别保护或交 Agent。
    if unit == "AGENTS.md" and _apply_agents_sectioned(src, changed):
        print("AGENTS.md 已按标题协议处理：开发原则强制更新，目录规则交 agent 合并，项目介绍保留")
        return
    if not decision:
        print(f"裁定单元 {unit} 未提供决策，跳过（待 agent 处理）")
        return
    if unit == "AGENTS.md":
        if _apply_agents_sectioned(src, changed):
            return
    if decision in ("merge", "merge_into_consumer"):
        print(f"裁定单元 {unit} 为 merge：由 agent 编辑消费文件完成语义合并，脚本不整文件覆盖")
        return
    if decision not in ("update", "update_from_template", "keep", "keep_consumer"):
        print(f"裁定单元 {unit} 非法决策 {decision!r}，跳过")
        return
    if decision in ("keep", "keep_consumer"):
        return
    s = src / unit
    d = CONSUMER / unit
    if d.is_symlink():
        d = d.resolve()
    if not s.exists():
        return
    if not d.exists() or _file_differs(s, d):
        d.parent.mkdir(parents=True, exist_ok=True)
        _stage_rollback(d)
        shutil.copy2(s, d)
        changed.add(d)


def _run_tests(consumer: Path) -> bool:
    r = subprocess.run(
        list(CONSUMER_TEST_COMMAND), cwd=str(consumer),
        capture_output=True, text=True, encoding="utf-8", errors="replace",
        timeout=CONSUMER_TEST_TIMEOUT,
    )
    if r.returncode != 0:
        print(r.stdout[-2000:] if r.stdout else "", file=sys.stderr)
        print(r.stderr[-2000:] if r.stderr else "", file=sys.stderr)
        return False
    return True


# ---------------------------------------------------------------------------
# 子命令
# ---------------------------------------------------------------------------

def cmd_init(args: argparse.Namespace) -> int:
    if not args.source:
        raise SyncError("init 需要 --source <path|url>")
    if not STATE_PATH.exists():
        # 旧布局 state 迁移：字段级带过 user_prompts / last_synced_*（新路径不存在时才读）。
        legacy = None
        if LEGACY_STATE_PATH.exists():
            try:
                legacy = json.loads(LEGACY_STATE_PATH.read_text(encoding="utf-8"))
            except (OSError, json.JSONDecodeError):
                legacy = None
        base = legacy if isinstance(legacy, dict) else {
            "template_source": None,
            "last_synced_commit": None,
            "last_synced_at": None,
            "user_prompts": [],
        }
        write_state(base)
        if legacy is not None:
            print(f"已迁移旧布局 state：{LEGACY_STATE_PATH.relative_to(CONSUMER).as_posix()} → {STATE_PATH.relative_to(CONSUMER).as_posix()}")
    data = read_state()
    kind = "path" if Path(args.source).expanduser().exists() else "url"
    data["template_source"] = {"kind": kind, "value": str(Path(args.source).expanduser().resolve() if kind == "path" else args.source)}
    write_state(data)
    if LEGACY_STATE_PATH.exists():
        try:
            LEGACY_STATE_PATH.unlink()
            print(f"旧布局 state 已移除：{LEGACY_STATE_PATH.relative_to(CONSUMER).as_posix()}")
        except OSError:
            pass
    print(f"template_source 已写：kind={kind}, value={data['template_source']['value']}")
    return 0


def cmd_status(args: argparse.Namespace) -> int:
    state = read_state()
    if not state:
        print("未初始化：无 sync_state.json。先运行 init --source <path|url>")
        return 0
    src = resolve_src(state)
    head = _git(src, "rev-parse", "--short", "HEAD").stdout.strip() or "?"
    dirty = src_dirty(src)
    prompts = active_prompts(state)
    print(f"template_source: {state['template_source']['kind']} {state['template_source']['value']}")
    print(f"SRC HEAD: {head}  dirty={dirty}")
    print(f"last_synced_commit: {state.get('last_synced_commit')}")
    print(f"last_synced_at: {state.get('last_synced_at')}")
    print(f"生效 user_prompts: {len(prompts)} 条（共 {len(state.get('user_prompts', []))} 条）")
    for i, p in enumerate(prompts):
        print(f"  #{i} {p.get('at')} {p.get('text')}")
    print("\n硬同步差异:")
    for item in hard_sync_status(src):
        mark = {"write": "需写入", "delete": "需删除", "same": "一致"}[item["state"]]
        print(f"  {item['state']:6s} {item['rel']}  ({mark})")
    print("\nskill:")
    for item in skill_status(src):
        mark = {"override": "强制覆盖", "same": "一致", "keep": "保留", "stale": "旧真实目录待转软链"}[item["action"]]
        print(f"  {item['action']:8s} {item['name']}  ({mark})")
    print("\n裁定单元:")
    for item in shared_status(src):
        print(f"  {item['cls']:14s} {item['unit']}")
    migrations, worktrees, migration_errors = workflow_migration_status(src)
    print("\nworkflow schema 强制迁移:")
    if migration_errors:
        for error in migration_errors:
            print(f"  BLOCKED: {error}")
    if worktrees:
        print("  BLOCKED: 先完成或 rewind task worktree：" + ", ".join(branch for _, branch in worktrees))
    if migrations:
        for path in migrations:
            print(f"  migrate {path}")
    if not migration_errors and not worktrees and not migrations:
        print("  无")
    print("\nformat 豁免 (.prettierignore):")
    dst = CONSUMER / ".prettierignore"
    existing = {ln.strip() for ln in dst.read_text(encoding="utf-8").splitlines()} if dst.exists() else set()
    missing = [r for r in PRETTIERIGNORE_TEMPLATE_RULES if r not in existing]
    if missing:
        for rule in missing:
            print(f"  缺失 {rule}（apply 追加）")
    else:
        print("  齐全")
    for warning in retired_template_warnings():
        print(f"  STALE: {warning}")
    return 0


def _md_table(headers: list[str], rows: list[list[str]]) -> str:
    lines = ["| " + " | ".join(headers) + " |", "|" + "|".join(["------"] * len(headers)) + "|"]
    for row in rows:
        lines.append("| " + " | ".join(row) + " |")
    return "\n".join(lines)


def cmd_plan(args: argparse.Namespace) -> int:
    state = read_state()
    if not state:
        print("未初始化：无 sync_state.json。先运行 init --source <path|url>")
        return 0
    src = resolve_src(state)
    assert_not_self(src)
    head = _git(src, "rev-parse", "--short", "HEAD").stdout.strip() or "?"
    dirty = src_dirty(src)
    prompts = active_prompts(state)

    print("## repo-template-sync 预览")
    print(f"\nSRC: {state['template_source']['value']} @ {head}  dirty={dirty}")
    print("\n### 站立指令 user_prompts（裁定优先）")
    if prompts:
        rows = [[str(i), p.get("at", ""), p.get("text", "")] for i, p in enumerate(prompts)]
        print(_md_table(["#", "at", "text"], rows))
    else:
        print("无")

    print("\n### 强制覆盖（同步分类）")
    rows = []
    for item in hard_sync_status(src):
        if item["state"] != "same":
            rows.append([item["rel"], item["state"], "树对树覆盖" if item["state"] == "write" else "删除"])
    for item in skill_status(src):
        if item["action"] == "override":
            rows.append([f".repo_template/skills/{item['name']}", "both_differ", "强制覆盖（含 front matter）"])
        elif item["action"] == "stale":
            rows.append([f".agents/skills/{item['name']}", "stale_dir", "旧真实目录转软链（备份原内容）"])
        elif item["action"] == "keep":
            rows.append([f".agents/skills/{item['name']}", "consumer_only", "保留（禁止删）"])
    print(_md_table(["单元", "分类", "处置"], rows))

    print("\n### 裁定同步 — 逐项（有 diff 必出现）")
    rows = []
    blocked = prompt_substrings(state)
    agents_is_sectioned = agents_section_status(src) is not None
    for item in shared_status(src):
        if item["unit"] == "AGENTS.md" and agents_is_sectioned:
            continue
        if item["cls"] == "both_identical":
            continue
        if item["unit"] == ".gitignore" and item["cls"] in ("both_differ", "template_only"):
            disp = "merge_into_consumer" + ("（遵从 prompt 拦截）" if blocked else "")
        elif item["cls"] == "template_only":
            disp = "建议 update_from_template"
        elif item["cls"] == "consumer_only":
            disp = "keep_consumer"
        else:
            disp = "ask_user / agent 决策"
        rows.append([item["unit"], item["cls"], disp])
    print(_md_table(["单元", "分类", "disposition"], rows))

    print("\n### AGENTS.md 分区")
    section_status = agents_section_status(src)
    if section_status is None:
        print("未识别到完整标题协议：需要 ## 目录与读写规则、## 开发原则")
    else:
        print(_md_table(["区段", "状态", "处置"], [
            ["项目介绍", section_status["intro"], "绝不更新，保留消费仓内容"],
            ["目录与读写规则", section_status["merge"], "agent 语义合并，脚本不覆盖"],
            ["开发原则", section_status["force"], "每轮强制从模板更新"],
        ]))

    print("\n### 软链")
    rows = []
    for item in symlink_status():
        mark = {"ok": "正确", "repair": "需建/修", "unmanaged": "非本机制，不碰"}[item["state"]]
        rows.append([f".claude/skills/{item['name']}", item["state"], mark])
    print(_md_table(["路径", "状态", "说明"], rows))

    print("\n### format 豁免（.prettierignore 机械合并）")
    dst = CONSUMER / ".prettierignore"
    existing = {ln.strip() for ln in dst.read_text(encoding="utf-8").splitlines()} if dst.exists() else set()
    missing = [r for r in PRETTIERIGNORE_TEMPLATE_RULES if r not in existing]
    if missing:
        rows = [[rule, "缺失", "apply 追加"] for rule in missing]
        print(_md_table(["规则", "状态", "处置"], rows))
    else:
        print("齐全（模板自有路径已豁免）")
    for warning in retired_template_warnings():
        print(f"- STALE: {warning}")

    print("\n### workflow schema 强制迁移")
    migrations, worktrees, migration_errors = workflow_migration_status(src)
    if migration_errors:
        print("BLOCKED：以下文档无法自动迁移：")
        for error in migration_errors:
            print(f"- {error}")
    if worktrees:
        print("BLOCKED：先完成或 rewind 已登记 task worktree：")
        for root, branch in worktrees:
            print(f"- {branch} @ {root}")
    if migrations:
        for path in migrations:
            print(f"- {path}")
    if not migration_errors and not worktrees and not migrations:
        print("无")

    print("\n### state 推进预期")
    if dirty:
        print(f"SRC dirty，apply 可写盘但**不**推进 last_synced_commit")
    else:
        print(f"apply 通过后推进 last_synced_commit -> {head}")
    return 0


def _apply_sync_write(src: Path, decisions: dict[str, str], changed: set[Path], blocked: list[str]) -> None:
    """apply 的写盘主体；OSError 由调用方回滚（F16）。"""
    for rel in HARD_SYNC_DIRS:
        s, d = src / rel, CONSUMER / rel
        if s.exists():
            sync_dir(s, d, changed)
        elif d.exists():
            _stage_rollback(d)
            shutil.rmtree(d)
            changed.add(d)
    for rel in HARD_SYNC_FILES:
        sync_file(src / rel, CONSUMER / rel, changed)

    for report in force_migrate_workflow_tasks(changed):
        print(f"提示: {report}")
    reports = repair_symlinks(changed)
    for r in reports:
        print(f"提示: {r}")
    for r in sync_opencode_commands(changed):
        print(f"提示: {r}")

    if (src / ".gitignore").exists():
        info = merge_gitignore(src, blocked, changed)
        if info["added"]:
            print(f".gitignore 追加 {len(info['added'])} 条（模板独有）")
        if info["removed"]:
            print(f".gitignore 删除 {len(info['removed'])} 条（prompt 禁止 ignore）")
    prettier_info = merge_prettierignore(changed)
    if prettier_info["added"]:
        print(f".prettierignore 追加 {len(prettier_info['added'])} 条（模板自有路径豁免 prettier）")
    for warning in retired_template_warnings():
        print(f"提示: {warning}")
    merge_mcp(src, changed)

    for unit in SHARED_FILES:
        if unit == ".gitignore":
            continue
        decision = decisions.get(unit)
        _apply_shared_unit(unit, decision, src, changed)


def cmd_apply(args: argparse.Namespace) -> int:
    state = read_state()
    if not state:
        raise SyncError("未初始化：无 sync_state.json。先运行 init --source <path|url>")
    src = resolve_src(state)
    assert_not_self(src)
    decisions = getattr(args, "decisions", None) or {}
    changed: set[Path] = set()
    blocked = prompt_substrings(state)

    try:
        _apply_sync_write(src, decisions, changed, blocked)
    except (OSError, SyncError) as error:
        _rollback_changes()
        raise SyncError(f"apply 中途失败，已回滚已覆盖文件（{error}）") from error

    if not args.skip_tests:
        if not _run_tests(CONSUMER):
            print("pytest .repo_template/tests/ -m contract 失败，不推进 state", file=sys.stderr)
            _cleanup_rollback()
            return 1
    else:
        print("跳过测试验证（--skip-tests）")

    dirty = src_dirty(src)
    if not dirty:
        head = _git(src, "rev-parse", "HEAD").stdout.strip()
        state["last_synced_commit"] = head
    state["last_synced_at"] = _now_iso()
    write_state(state)

    print("\n=== 改动路径清单（commit 门禁点名 add）===")
    for path in sorted(changed, key=str):
        print(_rel(path))
    if not changed:
        print("（无改动）")
    print(f"\nstate 推进：last_synced_commit={'已更新' if not dirty else 'SRC dirty，未推进'}, "
          f"last_synced_at={state['last_synced_at']}")
    _cleanup_rollback()
    return 0


def cmd_prompt(args: argparse.Namespace) -> int:
    state = read_state()
    if not state:
        raise SyncError("未初始化：无 sync_state.json。先运行 init --source <path|url>")
    if args.action == "list":
        for i, p in enumerate(state.get("user_prompts", [])):
            rev = " [revoked]" if p.get("revoked") else ""
            print(f"#{i}{rev} {p.get('at')} tags={p.get('tags', [])} {p.get('text')}")
        return 0
    prompts = state.setdefault("user_prompts", [])
    if args.action == "add":
        if not args.text:
            raise SyncError("prompt add 需要 --text")
        tags = [t.strip().lower() for t in (args.tags or "").split(",") if t.strip()]
        for p in prompts:
            if p.get("revoked"):
                continue
            old_tags = {str(t).lower() for t in p.get("tags", [])}
            if old_tags & set(tags):
                p["revoked"] = True
        prompts.append({"at": _now_iso(), "text": args.text, "tags": tags, "revoked": False})
        write_state(state)
        print(f"已登记 prompt #{len(prompts) - 1}: {args.text}")
        return 0
    if args.action == "revoke":
        idx = args.id
        if idx is None or not (0 <= idx < len(prompts)):
            raise SyncError(f"revoke 需要合法 --id（0..{len(prompts) - 1}）")
        prompts[idx]["revoked"] = True
        write_state(state)
        print(f"已作废 prompt #{idx}")
        return 0
    return 0


def cmd_prep(args: argparse.Namespace) -> int:
    """同步工具自举：单向覆盖（新增+覆盖，不删除）core skill 与 .repo_template/scripts，并建软链。

    由 repo-template-sync 启动器在每轮同步前调用，保证随后执行的 core skill 与脚本能力
    为模板源最新版。不写 state（不推进 last_synced_*）。
    """
    state = read_state()
    if not state:
        raise SyncError("未初始化：无 sync_state.json。先运行 init --source <path|url>")
    src = resolve_src(state)
    assert_not_self(src)
    changed: set[Path] = set()

    src_tool = src / ".repo_template/scripts"
    if src_tool.exists():
        sync_dir_oneway(src_tool, CONSUMER / ".repo_template/scripts", changed)

    src_core = src / ".repo_template/skills/repo-template-sync-core"
    if src_core.exists():
        sync_skill(src_core, SKILLS_SRC / "repo-template-sync-core", changed)

    reports = repair_symlinks(changed)
    for r in reports:
        print(f"提示: {r}")
    for r in sync_opencode_commands(changed):
        print(f"提示: {r}")

    print("=== prep 改动路径清单（单向覆盖，未删除）===")
    for path in sorted(changed, key=str):
        print(_rel(path))
    if not changed:
        print("（工具已是最新，无改动）")
    return 0


def cmd_install_hooks(args: argparse.Namespace) -> int:
    """幂等设置 core.hooksPath 指向工具链 hooks。

    git 对相对路径按仓库顶层解析。消费仓 hooks 在 `.repo_template/hooks`；
    工厂仓产物在 `repo/` 下时须写成 `repo/.repo_template/hooks`。已有其它
    hooksPath 时拒绝，须 --force。
    """
    hooks_dir = CONSUMER / ".repo_template" / "hooks"
    hook_script = hooks_dir / "pre-commit"
    if not hook_script.is_file():
        print("错误: 缺 hook 脚本 .repo_template/hooks/pre-commit", file=sys.stderr)
        return 1
    if not os.access(hook_script, os.X_OK):
        print("错误: .repo_template/hooks/pre-commit 不可执行", file=sys.stderr)
        return 1
    toplevel = _git(CONSUMER, "rev-parse", "--show-toplevel").stdout.strip()
    if not toplevel:
        print("错误: 无法解析 git 仓库顶层", file=sys.stderr)
        return 1
    try:
        hooks_rel = hooks_dir.resolve().relative_to(Path(toplevel).resolve()).as_posix()
    except ValueError:
        print(
            f"错误: hooks 目录不在仓库顶层内：{hooks_dir} / {toplevel}",
            file=sys.stderr,
        )
        return 1
    current = _git(CONSUMER, "config", "--get", "core.hooksPath").stdout.strip()
    if current == hooks_rel:
        print(f"core.hooksPath 已指向 {hooks_rel}，无需改动")
        return 0
    if current and not getattr(args, "force", False):
        print(
            f"错误: core.hooksPath 已是 {current}；"
            f"覆盖为 {hooks_rel} 须加 --force",
            file=sys.stderr,
        )
        return 1
    result = _git(CONSUMER, "config", "core.hooksPath", hooks_rel)
    if result.returncode != 0:
        print(f"错误: 设置 core.hooksPath 失败：{result.stderr.strip()}", file=sys.stderr)
        return 1
    print(f"core.hooksPath 已设为 {hooks_rel}")
    return 0


def cmd_link_skills(args: argparse.Namespace) -> int:
    changed: set[Path] = set()
    reports = repair_symlinks(changed)
    reports += sync_opencode_commands(changed)
    for r in reports:
        print(f"提示: {r}")
    if not changed:
        print("软链均已正确")
    for path in sorted(changed, key=str):
        print(f"已修: {_rel(path)}")
    return 0


def _now_iso() -> str:
    import datetime
    return datetime.datetime.now(datetime.timezone(datetime.timedelta(hours=8))).strftime("%Y-%m-%dT%H:%M:%S+08:00")


def _parse_decisions(items: list[str]) -> dict[str, str]:
    out: dict[str, str] = {}
    for item in items:
        if ":" not in item:
            raise SyncError(f"--decision 格式应为 UNIT:DISPOSITION，收到 {item!r}")
        unit, disp = item.split(":", 1)
        out[unit] = disp
    return out


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="repo-template-sync 机械化执行器")
    sub = parser.add_subparsers(dest="cmd", required=True)

    init = sub.add_parser("init", help="初始化 sync_state.json 的 template_source")
    init.add_argument("--source", help="模板源：本机路径或 git remote URL")
    init.set_defaults(func=cmd_init)

    sub.add_parser("status", help="读取状态与差异摘要").set_defaults(func=cmd_status)
    sub.add_parser("plan", help="计算差异预览（零写盘）").set_defaults(func=cmd_plan)
    sub.add_parser("prep", help="同步工具自举：单向覆盖 core skill 与 .repo_template/scripts，建软链").set_defaults(func=cmd_prep)

    apply = sub.add_parser("apply", help="执行对齐写盘")
    apply.add_argument("--decision", action="append", default=[], metavar="UNIT:DISP",
                       help="裁定单元决策（可重复），如 AGENTS.md:update / AGENTS.md:keep")
    apply.add_argument("--skip-tests", action="store_true", help="跳过模板契约测试（-m contract）")
    apply.set_defaults(func=cmd_apply)

    prompt = sub.add_parser("prompt", help="管理 user_prompts")
    prompt.add_argument("action", choices=["list", "add", "revoke"])
    prompt.add_argument("--text", help="prompt 正文（add 用）")
    prompt.add_argument("--tags", help="逗号分隔 tags（add 用）")
    prompt.add_argument("--id", type=int, help="条目下标（revoke 用）")
    prompt.set_defaults(func=cmd_prompt)

    sub.add_parser("link-skills", help="校验并修复宿主 skills 软链，生成 .opencode/commands 命令薄层").set_defaults(func=cmd_link_skills)
    hooks = sub.add_parser(
        "install-hooks",
        help="幂等设置 core.hooksPath 指向工具链 hooks（已有其它值须 --force）",
    )
    hooks.add_argument("--force", action="store_true", help="覆盖已有的 core.hooksPath")
    hooks.set_defaults(func=cmd_install_hooks)
    return parser


def main(argv: list[str] | None = None) -> None:
    parser = build_parser()
    args = parser.parse_args(argv)
    if getattr(args, "cmd", None) == "apply":
        args.decisions = _parse_decisions(args.decision)
    try:
        sys.exit(args.func(args))
    except SyncError as e:
        print(f"错误: {e}", file=sys.stderr)
        sys.exit(1)
    except OSError as e:
        # 文件系统错误统一入口：裸 OSError 会中断多步写盘且无友好消息（F16）
        print(f"错误: {e}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
        sys.stderr.reconfigure(encoding="utf-8", errors="replace")
    main()
